// <auto-generated />
using System;
using CrudEf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudEf.Migrations
{
    [DbContext(typeof(SafariContext))]
    [Migration("20260609234458_NuevosCamposAnimal")]
    partial class NuevosCamposAnimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("CrudEf.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Energia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaVivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("FechaMuerte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reserva")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Energia = 80,
                            Especie = "leon",
                            EstaVivo = false,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaMuerte = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "serengeti",
                            Sexo = "M"
                        },
                        new
                        {
                            Id = 2,
                            Energia = 75,
                            Especie = "leon",
                            EstaVivo = false,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaMuerte = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "masai_mara",
                            Sexo = "H"
                        },
                        new
                        {
                            Id = 3,
                            Energia = 40,
                            Especie = "tortuga",
                            EstaVivo = false,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaMuerte = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "galapagos",
                            Sexo = "H"
                        },
                        new
                        {
                            Id = 4,
                            Energia = 60,
                            Especie = "pinguino",
                            EstaVivo = false,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaMuerte = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "patagonia",
                            Sexo = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
