// <auto-generated />
using System;
using CrudEf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudEf.Migrations
{
    [DbContext(typeof(SafariContext))]
    partial class SafariContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("CrudEf.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Energia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("energia");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("especie");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_alta")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Reserva")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reserva");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.ToTable("animales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Energia = 80,
                            Especie = "leon",
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "serengeti",
                            Sexo = "M"
                        },
                        new
                        {
                            Id = 2,
                            Energia = 75,
                            Especie = "leon",
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "masai_mara",
                            Sexo = "H"
                        },
                        new
                        {
                            Id = 3,
                            Energia = 40,
                            Especie = "tortuga",
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "galapagos",
                            Sexo = "H"
                        },
                        new
                        {
                            Id = 4,
                            Energia = 60,
                            Especie = "pinguino",
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reserva = "patagonia",
                            Sexo = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
